blog:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/blog
    database: blog
    host: localhost
    port: 3306
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    #password: auth(123465)
    database: 1
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: Asuka
    # 设置jwt过期时间
    admin-ttl: 360000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: sumika
    user-ttl: 360000000
    user-token-name: authentication







