server:
  port: 8080

spring:
  profiles:
    active: dev    #测试环境

  datasource:
    driver-class-name: ${blog.datasource.driver-class-name}
    url: jdbc:mysql://${blog.datasource.host}:${blog.datasource.port}/${blog.datasource.database}
    username: root
    password: 1234
  data:
    redis:
      port: ${blog.redis.port}
      host: ${blog.datasource.host}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.asukasumika.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info



knife4j:
  enable: true
  openapi:
    title: Asuka的个人博客
    description: "Asuka的个人博客接口文档"
    email: 1626928042@qq.com
    concat: Asuka
    url:
    version: v2.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.asukasumika.controller


















